language: node_js
node_js:
  - node
script:
  - npm run build
cache:
  directories:
    - node_modules
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: dist
  repo: pushresume/pushresume.github.io
  committer-from-gh: true
  target-branch: master
  project-name: frontend
  on:
    branch: master
